apiVersion: v1
kind: Service
metadata:
  labels:
    name: my-awesome-front-svc
  name: my-awesome-front-svc
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30080
  selector:
    app: front-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-awesome-front
spec:
  replicas: 2

  template:
    metadata:
      labels:
        app: front-app

    spec:
      containers:   
      - name: my-awesome-frontend-app
        image: 172.17.4.1:5000/my-awesome-frontend-app:0.0.4
        imagePullPolicy: Always
