apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-awesome-frontend-app
spec:
  replicas: 2

  template:
    metadata:
      labels:
        app: front-chat

    spec:
      containers:   
      - name: my-awesome-frontend-app
        image: 172.17.4.1:5000/my-awesome-frontend-app:0.0.3
        imagePullPolicy: Always
