apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: my-awesome-app
spec:
  replicas: 3
  
  selector:
    matchLabels:
      app: chat

  template:
    metadata:
      labels:
        app: chat

    spec:
      containers:   
      - name: my-awesome-app
        image: 172.17.4.1:5000/my-awesome-app:0.0.2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
