apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-awesome-backend-app
spec:
  replicas: 3
      
  minReadySeconds: 5 #time between actions
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 #Amount of pods more than desired during deployment
      maxUnavailable: 1  #Amount of pods can be unavailable during the deployment

  template:
    metadata:
      labels:
        app: back-chat

    spec:
      containers:   
      - name: my-awesome-backend-app
        image: 172.17.4.1:5000/my-awesome-backend-app:0.0.2
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 15
          timeoutSeconds: 1
