apiVersion: v1
kind: Pod
metadata:
  name: one-pod
spec:

  restartPolicy: Never

  volumes:
  - name: shared-data
    emptyDir: {}

  containers:

  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html

  - name: echo-container
    image: debian
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "echo I am your co-container echo > /pod-data/index.html"]

  - name: curl-container
    image: solidnerd/curl:7.52.1
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hi; done"]

