apiVersion: v1
kind: Pod
metadata:
  name: single-pod
spec:

  restartPolicy: Never

  volumes:
  - name: shared-data
    emptyDir: {}

  containers:

  - name: my-awesome-app
    image: 172.17.4.1:5000/my-awesome-app:0.0.1
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 15
      timeoutSeconds: 1
    imagePullPolicy: Always
    env:
    - name: NODE_ENV
      value: production
    volumeMounts:
    - name: shared-data
      mountPath: /var/www/app/config

  - name: echo-container
    image: 172.17.4.1:5000/debian:0.0.1
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "echo title=my-title > /pod-data/config.ini"]

  - name: curl-container
    image: 172.17.4.1:5000/curl-container:0.0.1
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hi; done"]

