apiVersion: v1
kind: Pod
metadata:
  name: single-pod
spec:

  containers:

  - name: my-awesome-app
    image: 10.101.91.182:5000/my-awesome-app:0.0.1
    volumeMounts:
    - name: nfs
      mountPath: /var/www/app/config

  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: nfs
